input:
  path: data-er-input
  type: csv
sources-pairs:
  - sourcePair: [trade, product]
    fields: [ "trade_id", "product_id"]
  - sourcePair: [trade, counterparty]
    fields: [ "trade_id", "ctpy_id"]
output:
  path: /tmp/data-er/
  type: csv