input:
  path: data-input
sourcesPairs:
  - name: "Trade&Product ER-Joining-one source pair - no id"
    forcedRun: true
    sourcePair: ["trade.csv", "product.csv"]
    joinFields:
      - source1Field: "t_pid"
        source2Field: "p_id"
        weight: 0.9
      - source1Field: "system"
        source2Field: "sys"
        weight: 0.1
    source1Filters:
      - field: site
        values: ["CN"]
      - field: t_date
        values: ["20200715"]
    source2Filters:
      - field: type
        values: ["fund"]
    statePath: tp_stat_noid.txt
    source1AdditionalExtractFields: ["t_user", "system", "t_pid"]
    source2AdditionalExtractFields: ["p_id", "p_name", "sys"]
    joinResultFile: trade-product/tp-mapping-no-id
output:
  path: data-output
  dataType: csv
  overwriteOnExist: true
  showSimilarity: true
  connectedClustering: false
useFlow: EDJoinFlow
