flows:
  - name: EDJoinFlow
    options:
      - {key: type, value: SSJoin}
      - {key: algorithm, value: EDJoin}
      - {key: q, value: 2}
      - {key: threshold, value: 1}
  - name: EDParaJoinFlow
    options:
      - {key: type, value: SSParaJoin}
      - {key: algorithm, value: EDJoin}
      - {key: joinPoolSize, value: 4}
      - {key: joinMaxDuration, value: 60}
      - {key: joinMaxDurationUnit, value: sec}
      - {key: q, value: 2}
      - {key: threshold, value: 1}
  - name: EDBatchJoinFlow
    options:
      - {key: type, value: SSBatchJoin}
      - {key: algorithm, value: EDJoin}
      - {key: q, value: 2}
      - {key: threshold, value: 1}
  - name: End2EndFlow
    options:
      - {key: threshold, value: 0.6}
      - {key: type, value: End2End}